# Generated by Django 5.2.14 on 2026-05-30 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Bill (Electricity)'), ('travel', 'Corporate Travel (Concur)')], max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(default=list)),
                ('ingested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.organization')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField()),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('parse_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('supplier_or_site', models.CharField(blank=True, max_length=255)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion (Fuel)'), ('mobile_combustion', 'Mobile Combustion (Fuel)'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Air'), ('business_travel_rail', 'Business Travel — Rail'), ('business_travel_car', 'Business Travel — Car/Rental')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activity_unit', models.CharField(max_length=30)),
                ('activity_unit_original', models.CharField(blank=True, max_length=30)),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('emission_factor_source', models.CharField(max_length=100)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending_review', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionbatch')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.organization')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
    ]
